### ISSUE TITLE
The TrueType font null does not contain a 'cmap' table

### ISSUE THREAD

**Issue by denisab85** [grasshopper7/pdfextentreporter#1]
When multiple reports are created, the first report builds normally, but the second and all subsequent reports don't build and throw an exception:

`
java.io.IOException: The TrueType font null does not contain a 'cmap' table
	at org.apache.fontbox.ttf.TrueTypeFont.getUnicodeCmapImpl(TrueTypeFont.java:561)
	at org.apache.fontbox.ttf.TrueTypeFont.getUnicodeCmapLookup(TrueTypeFont.java:541)
	at org.apache.fontbox.ttf.TrueTypeFont.getUnicodeCmapLookup(TrueTypeFont.java:527)
	at org.apache.fontbox.ttf.TTFSubsetter.<init>(TTFSubsetter.java:90)
	at org.apache.pdfbox.pdmodel.font.TrueTypeEmbedder.subset(TrueTypeEmbedder.java:347)
	at org.apache.pdfbox.pdmodel.font.PDType0Font.subset(PDType0Font.java:256)
	at org.apache.pdfbox.pdmodel.PDDocument.save(PDDocument.java:1367)
	at org.apache.pdfbox.pdmodel.PDDocument.save(PDDocument.java:1342)
	at tech.grasshopper.reporter.ReportGenerator.generate(ReportGenerator.java:92)
	at tech.grasshopper.reporter.ExtentPDFReporter.flush(ExtentPDFReporter.java:105)
	at tech.grasshopper.reporter.ExtentPDFReporter.access$100(ExtentPDFReporter.java:20)
	at tech.grasshopper.reporter.ExtentPDFReporter$1.onNext(ExtentPDFReporter.java:84)
	at tech.grasshopper.reporter.ExtentPDFReporter$1.onNext(ExtentPDFReporter.java:77)
	at io.reactivex.rxjava3.subjects.PublishSubject$PublishDisposable.onNext(PublishSubject.java:310)
	at io.reactivex.rxjava3.subjects.PublishSubject.onNext(PublishSubject.java:226)
	at com.aventstack.extentreports.ReactiveSubject.onFlush(ReactiveSubject.java:83)
	at com.aventstack.extentreports.AbstractProcessor.onFlush(AbstractProcessor.java:85)
	at com.aventstack.extentreports.ExtentReports.flush(ExtentReports.java:279)
	at Test.main(Test.java:13)
`

This doesn't happen if ExtentSparkReporter is used.

Code sample to reproduce the bug:
`
import com.aventstack.extentreports.ExtentReports;
import tech.grasshopper.reporter.ExtentPDFReporter;

import java.io.File;

public class Test {

    public static void main(String[] args) {
        for (int i = 0; i < 3; i++) {
            System.out.println("Report " + i);
            ExtentReports testReport = new ExtentReports();
            testReport.attachReporter(new ExtentPDFReporter(new File(i + ".pdf")));
            testReport.flush();
        }
    }
    
}
`

**Comment by grasshopper7** [comment]
Multiple instances of the same reporter. Never crossed my mind. 
The problem should be due to statics in ReportFont class, which is the best scenario. Else if it is due to pdfbox font loading then it will be a long haul.
Thanks.

**Comment by grasshopper7** [comment]
Supported in 1.0.0. Have released should be available in Maven in hours.

**Comment by denisab85** [comment]
Verified with v1.0.0. Multiple PDFs are saved. Fixed.

**Comment by shilpalegalsimpli** [comment]
Hi https://github.com/grasshopper7 still i am unable to generate multiple PDFs for multiple runners via maven test in eclipse in a single run for both runners: Please let me know what mistake i have done..this task is very imp for me and my organization.  
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "http://testng.org/testng-1.0.dtd">
<suite name="Suite">

	
	<test name="ExecuteCucumberRunnerTest">
	
		<classes>
			
			
			<class name="runnerFiles.ExecuteCucumberRunnerTest" />
			
			
		</classes>
	</test> 
	
	<test name="ExecuteCucumberRunnerTest2">
	
		<classes>
			
			
			<class name="runnerFiles.ExecuteCucumberRunnerTest2" />
			
			
		</classes>
	</test> 

</suite>
